export async function fetchManualEvents() {
  return [
    {
      source: 'manual-event',
      sourceId: 'manual-cosmobeauty-seoul-2026',
      category: '전시·박람회',
      title: '2026 코스모뷰티서울 (서울국제화장품·미용산업박람회)',
      summary: '1987년 시작된 국내 최초 뷰티 전문 박람회. 820여 부스, 약 15,000㎡ 규모로 헬스앤뷰티위크와 동시 개최. K-뷰티 트렌드, 신제품, OEM/ODM 상담.',
      org: '코스모뷰티서울',
      executor: '코스모뷰티서울',
      region: '서울',
      venue: '코엑스 A·B홀',
      field: '전시·박람회',
      hashtags: '박람회 #코스모뷰티서울 #뷰티 #화장품 #K뷰티 #코엑스',
      target: '뷰티 산업 관계자, 바이어, 일반 관람객',
      startDate: '2026-05-27',
      endDate: '2026-05-29',
      posted: '2026-01-10',
      url: 'https://www.cosmobeautyseoul.com',
      relevance: 85,
      raw: null,
    },
    {
      source: 'manual-event',
      sourceId: 'manual-health-beauty-week-2026',
      category: '전시·박람회',
      title: '2026 헬스앤뷰티위크 (국제건강산업박람회)',
      summary: '코스모뷰티서울과 동시 개최되는 국제건강산업박람회. 이너뷰티, 헬스, 웰니스 분야.',
      org: '헬스앤뷰티위크',
      executor: '헬스앤뷰티위크',
      region: '서울',
      venue: '코엑스 A·B홀',
      field: '전시·박람회',
      hashtags: '박람회 #헬스앤뷰티위크 #이너뷰티 #헬스 #웰니스 #코엑스',
      target: '헬스·뷰티 산업 관계자, 바이어, 일반 관람객',
      startDate: '2026-05-27',
      endDate: '2026-05-29',
      posted: '2026-01-10',
      url: 'https://www.cosmobeautyseoul.com',
      relevance: 85,
      raw: null,
    },
    {
      source: 'manual-event',
      sourceId: 'manual-kbeauty-expo-korea-2026',
      category: '전시·박람회',
      title: '2026 K-뷰티 엑스포 코리아 (KBEAUTY EXPO KOREA)',
      summary: '국내 최대 규모의 뷰티 전문 박람회. 화장품, 미용기기, 헤어·네일, 메이크업 등 K-뷰티 전 분야 통합 전시.',
      org: 'KBEAUTY EXPO KOREA',
      executor: 'KBEAUTY EXPO KOREA',
      region: '경기',
      venue: '킨텍스 3·4·5홀 (일산)',
      field: '전시·박람회',
      hashtags: '박람회 #K뷰티 #뷰티 #화장품 #메이크업 #킨텍스',
      target: '뷰티 산업 관계자, 해외 바이어, 일반 관람객',
      startDate: '2026-10-15',
      endDate: '2026-10-17',
      posted: '2026-02-20',
      url: 'https://www.k-beautyexpo.co.kr',
      relevance: 90,
      raw: null,
    },
    {
      source: 'manual-event',
      sourceId: 'manual-nbifs-busan-2026',
      category: '전시·박람회',
      title: '제39회 2026 부산창업박람회 (NBIFS)',
      summary: '신사업·프랜차이즈·K-shop 중심 창업박람회. 뷰티샵 창업 관심자에게 유용.',
      org: '선인커뮤니티',
      executor: '선인커뮤니티',
      region: '부산',
      venue: '벡스코 제1전시장 2A홀',
      field: '전시·박람회',
      hashtags: '박람회 #창업 #프랜차이즈 #뷰티샵 #벡스코',
      target: '예비창업자, 프랜차이즈 가맹 희망자',
      startDate: '2026-04-23',
      endDate: '2026-04-25',
      posted: '2026-01-15',
      url: 'https://bexpo.co.kr',
      relevance: 80,
      raw: null,
    },
  ];
}
