export async function fetchManualEvents() {
  return [
    {
      source: 'manual-event',
      sourceId: 'manual-beauty-expo-2026-01',
      category: '전시·박람회',
      title: '2026 뷰티 & 라이프스타일 박람회',
      summary: '국내외 뷰티 브랜드와 라이프스타일 제품을 한자리에서 만나는 박람회입니다. 뷰티 트렌드, 신제품 전시, 체험 부스가 열립니다.',
      org: '뷰티페어코리아',
      executor: '뷰티페어코리아',
      region: '전국',
      venue: '코엑스 B홀',
      field: '전시·박람회',
      hashtags: '박람회 #뷰티 #라이프스타일 #전시',
      target: '뷰티 산업 관계자 및 소비자',
      startDate: '2026-03-12',
      endDate: '2026-03-15',
      posted: '2026-02-10',
      url: 'https://beautyfair.example.com',
      raw: null,
    },
    {
      source: 'manual-event',
      sourceId: 'manual-makeup-exhibition-2026-02',
      category: '전시·박람회',
      title: '글로벌 메이크업 아트 전시회',
      summary: '메이크업 아티스트, 브랜드, 교육 프로그램이 모이는 글로벌 전시회. 최신 메이크업 기술과 제품을 직접 체험할 수 있습니다.',
      org: 'K-Beauty Expo',
      executor: 'K-Beauty Expo',
      region: '서울',
      venue: '동대문디자인플라자(DDP)',
      field: '전시·박람회',
      hashtags: '전시회 #메이크업 #아트 #뷰티',
      target: '뷰티 전문가 및 일반 방문객',
      startDate: '2026-04-20',
      endDate: '2026-04-22',
      posted: '2026-03-01',
      url: 'https://kbeautyexpo.example.com',
      raw: null,
    },
    {
      source: 'manual-event',
      sourceId: 'manual-cosmetic-tradefair-2026-03',
      category: '전시·박람회',
      title: '국제 화장품 무역 박람회',
      summary: '화장품 바이어와 제조사가 참여하는 국제 무역 박람회. 비즈니스 상담, 신제품 발표, OEM/ODM 파트너십을 지원합니다.',
      org: '코스메틱 트레이드쇼',
      executor: '코스메틱 트레이드쇼',
      region: '부산',
      venue: '벡스코',
      field: '전시·박람회',
      hashtags: '박람회 #화장품 #무역 #OEM',
      target: '뷰티 제조업체, 바이어, 유통업체',
      startDate: '2026-05-08',
      endDate: '2026-05-10',
      posted: '2026-04-08',
      url: 'https://cosmetictrade.example.com',
      raw: null,
    },
  ];
}
